FROM node:16-alpine as base
WORKDIR /app

ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV
ARG RUNTIME_ENV
ENV RUNTIME_ENV=$RUNTIME_ENV

ARG WEB_API_URL
ENV WEB_API_URL=$WEB_API_URL
ARG REDWOOD_ENV_CUBEJS_API_URL
ENV REDWOOD_ENV_CUBEJS_API_URL=$REDWOOD_ENV_CUBEJS_API_URL

ARG TAG
ENV TAG=$TAG
ARG WEB_BUILD_TAG
ENV WEB_BUILD_TAG=$WEB_BUILD_TAG

# Copy
COPY api/package.json api/package.json
COPY web/package.json web/package.json
COPY package.json .
COPY yarn.lock .
COPY redwood.toml .
COPY graphql.config.js .
COPY .env.defaults .
COPY .yarn .yarn
COPY .yarnrc.yml .

# Install dependencies
RUN yarn install

###########################################################################################
# Build
###########################################################################################

FROM base as build

# Copy
COPY api api
COPY web web

# Build
RUN yarn rw build web

###########################################################################################
# Runner
###########################################################################################

FROM nginx

# Copy dist
COPY --from=build /app/web/dist /app/web/dist
COPY web/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8910

# Manually adding CMD instruction (from upstream) to bring in for analyzing
CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
